export const ADD_COUNTER = 'add_counter'
export const ADD_TO_CART = 'add_to_cart'
export const CHECK_ITEM = 'check_item'
export const CHECK_ALL = 'check_all'
export const INCREASE_NUM = 'increase_num'
export const DECREASE_NUM = 'decrease_num'
export const REMOVE_ITEM = 'remove_item'
